# Singleton service factory configuration/IoC injection
singletons:
# HandlerProvider implementation
- com.networknt.handler.HandlerProvider:
  - ch.sbb.integration.api.gateway.proxy.ProxyHandlerProvider
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.StartupHookProvider:
  - ch.sbb.integration.api.gateway.hooks.AdminStartupHook
# ShutdownHookProvider implementations, there are one to many and they are called in the same sequence defined.
- com.networknt.server.ShutdownHookProvider:
  - ch.sbb.integration.api.gateway.hooks.ThreeScaleAdapterShutdownHook
# MiddlewareHandler implementations, the calling sequence is as defined in the request/response chain.
#- com.networknt.handler.MiddlewareHandler:
  #Moved to handler.yml